# Server configs
server:
  # host: "0.0.0.0"
  host: "localhost"
  port: 8000
  prefix: "registry"
  jwt_access_secret: "epstein didnt kill himself"
  jwt_refresh_secret: "epstein didnt kill himself"
  new_orders_pipe_cap: 100

# Database credentials
registry_database:
  host: "localhost"
  port: "5432"
  db_name: "mydb"
  user: "user"
  password: "password"
  orders_table: "orders"
  order_items_table: "order_items_table"
  products_table: "products_table"

# Kafka configs
kafka:
  new_orders_topic: "new_orders"
  rejected_orders_topic: "rejected_orders_topic"
  group_id: "registry"
  external_clients_port: 9092
  internal_clients_port: 9093
  brokers: ["localhost:9093"]
  send_msg_timeout: 5
  consume_loop_tick: 500
  

# Logger configs
logger:
  level: "INFO" 


  