definitions:
  api.ErrResponseMsg:
    properties:
      message:
        type: string
    type: object
  api.HealthCheckResposne:
    properties:
      broker_conn:
        type: string
      wallet_trans_conn:
        type: string
      wallets_conn:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Service responsible for register and manage order requests.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Wallet service
  version: "1.0"
paths:
  /health:
    get:
      description: Check DB and broker client connections
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthCheckResposne'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponseMsg'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Healthcheck
      tags:
      - ops
swagger: "2.0"
